/* tslint:disable */
/* eslint-disable */
/**
 * Todolist RESTful API
 * OpenAPI for Todolist RESTful API
 *
 * OpenAPI spec version: 1
 * Contact: ikoafianando123@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ArrayTodolist } from '../models';
import { CreateOrUpdateTodolist } from '../models';
import { InlineResponse200 } from '../models';
import { Todolist } from '../models';
/**
 * TodolistApi - axios parameter creator
 * @export
 */
export const TodolistApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all todolist by default
         * @summary Get All Todolist
         * @param {boolean} [includeDone] Include done todolist in the result
         * @param {string} [name] Filter todolist by name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        todolistGet: async (includeDone?: boolean, name?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/todolist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication TodolistAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("X-API-Key")
                    : await configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }

            if (includeDone !== undefined) {
                localVarQueryParameter['include done'] = includeDone;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Create new todolist to database
         * @summary Create New Todolist
         * @param {CreateOrUpdateTodolist} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        todolistPost: async (body: CreateOrUpdateTodolist, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling todolistPost.');
            }
            const localVarPath = `/todolist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication TodolistAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("X-API-Key")
                    : await configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete existing todolist in database
         * @summary Delete existing Todolist
         * @param {string} todolistId Todolist id for updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        todollistTodolistIdDelete: async (todolistId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'todolistId' is not null or undefined
            if (todolistId === null || todolistId === undefined) {
                throw new RequiredError('todolistId','Required parameter todolistId was null or undefined when calling todollistTodolistIdDelete.');
            }
            const localVarPath = `/todollist/{todolistId}`
                .replace(`{${"todolistId"}}`, encodeURIComponent(String(todolistId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication TodolistAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("X-API-Key")
                    : await configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Update existing todolist in database
         * @summary Update existing Todolist
         * @param {CreateOrUpdateTodolist} body 
         * @param {string} todolistId Todolist id for updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        todollistTodolistIdPut: async (body: CreateOrUpdateTodolist, todolistId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling todollistTodolistIdPut.');
            }
            // verify required parameter 'todolistId' is not null or undefined
            if (todolistId === null || todolistId === undefined) {
                throw new RequiredError('todolistId','Required parameter todolistId was null or undefined when calling todollistTodolistIdPut.');
            }
            const localVarPath = `/todollist/{todolistId}`
                .replace(`{${"todolistId"}}`, encodeURIComponent(String(todolistId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication TodolistAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("X-API-Key")
                    : await configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TodolistApi - functional programming interface
 * @export
 */
export const TodolistApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get all todolist by default
         * @summary Get All Todolist
         * @param {boolean} [includeDone] Include done todolist in the result
         * @param {string} [name] Filter todolist by name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async todolistGet(includeDone?: boolean, name?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ArrayTodolist>> {
            const localVarAxiosArgs = await TodolistApiAxiosParamCreator(configuration).todolistGet(includeDone, name, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Create new todolist to database
         * @summary Create New Todolist
         * @param {CreateOrUpdateTodolist} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async todolistPost(body: CreateOrUpdateTodolist, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Todolist>> {
            const localVarAxiosArgs = await TodolistApiAxiosParamCreator(configuration).todolistPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Delete existing todolist in database
         * @summary Delete existing Todolist
         * @param {string} todolistId Todolist id for updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async todollistTodolistIdDelete(todolistId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await TodolistApiAxiosParamCreator(configuration).todollistTodolistIdDelete(todolistId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Update existing todolist in database
         * @summary Update existing Todolist
         * @param {CreateOrUpdateTodolist} body 
         * @param {string} todolistId Todolist id for updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async todollistTodolistIdPut(body: CreateOrUpdateTodolist, todolistId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Todolist>> {
            const localVarAxiosArgs = await TodolistApiAxiosParamCreator(configuration).todollistTodolistIdPut(body, todolistId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TodolistApi - factory interface
 * @export
 */
export const TodolistApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get all todolist by default
         * @summary Get All Todolist
         * @param {boolean} [includeDone] Include done todolist in the result
         * @param {string} [name] Filter todolist by name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        todolistGet(includeDone?: boolean, name?: string, options?: any): AxiosPromise<ArrayTodolist> {
            return TodolistApiFp(configuration).todolistGet(includeDone, name, options).then((request) => request(axios, basePath));
        },
        /**
         * Create new todolist to database
         * @summary Create New Todolist
         * @param {CreateOrUpdateTodolist} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        todolistPost(body: CreateOrUpdateTodolist, options?: any): AxiosPromise<Todolist> {
            return TodolistApiFp(configuration).todolistPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete existing todolist in database
         * @summary Delete existing Todolist
         * @param {string} todolistId Todolist id for updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        todollistTodolistIdDelete(todolistId: string, options?: any): AxiosPromise<InlineResponse200> {
            return TodolistApiFp(configuration).todollistTodolistIdDelete(todolistId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update existing todolist in database
         * @summary Update existing Todolist
         * @param {CreateOrUpdateTodolist} body 
         * @param {string} todolistId Todolist id for updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        todollistTodolistIdPut(body: CreateOrUpdateTodolist, todolistId: string, options?: any): AxiosPromise<Todolist> {
            return TodolistApiFp(configuration).todollistTodolistIdPut(body, todolistId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TodolistApi - object-oriented interface
 * @export
 * @class TodolistApi
 * @extends {BaseAPI}
 */
export class TodolistApi extends BaseAPI {
    /**
     * Get all todolist by default
     * @summary Get All Todolist
     * @param {boolean} [includeDone] Include done todolist in the result
     * @param {string} [name] Filter todolist by name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodolistApi
     */
    public todolistGet(includeDone?: boolean, name?: string, options?: any) {
        return TodolistApiFp(this.configuration).todolistGet(includeDone, name, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Create new todolist to database
     * @summary Create New Todolist
     * @param {CreateOrUpdateTodolist} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodolistApi
     */
    public todolistPost(body: CreateOrUpdateTodolist, options?: any) {
        return TodolistApiFp(this.configuration).todolistPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Delete existing todolist in database
     * @summary Delete existing Todolist
     * @param {string} todolistId Todolist id for updated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodolistApi
     */
    public todollistTodolistIdDelete(todolistId: string, options?: any) {
        return TodolistApiFp(this.configuration).todollistTodolistIdDelete(todolistId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Update existing todolist in database
     * @summary Update existing Todolist
     * @param {CreateOrUpdateTodolist} body 
     * @param {string} todolistId Todolist id for updated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodolistApi
     */
    public todollistTodolistIdPut(body: CreateOrUpdateTodolist, todolistId: string, options?: any) {
        return TodolistApiFp(this.configuration).todollistTodolistIdPut(body, todolistId, options).then((request) => request(this.axios, this.basePath));
    }
}
