/* tslint:disable */
/* eslint-disable */
/**
 * Todolist RESTful API
 * OpenAPI for Todolist RESTful API
 *
 * OpenAPI spec version: 1
 * Contact: ikoafianando123@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateOrUpdateTodolist
 */
export interface CreateOrUpdateTodolist {
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateTodolist
     */
    name?: any;
    /**
     * 
     * @type {number}
     * @memberof CreateOrUpdateTodolist
     */
    priority?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof CreateOrUpdateTodolist
     */
    tags?: any;
}
